language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: EMAIL
  api_key:
    secure: F3jQjZwen44twDy/Vn6RnyzmYQxZdEGZzfLWGbntp2kY65FbCMgolPobrybmq3yQSmBBSCFJ2MojqkvQ+zGjjT7wSk0V2L9OMK2k9O/RgxrAWP8gCdHTEiYdFV18MK6IK7QMhBBVDajMivfaPg0yuGYmgARBRi+RPmyrMQNBOD8N2KE7MEkY5o1diAmzVr2oDhg2nMj1R5naO6I3mu3e8Y8xyxTa9rR+f+87JCZUySjUVxWA7GqNkKyJ3a9ZeR0JKkpnSl2WdLd6ySOOMfd/W61CIwpjvKAK1o3UMb7x7GilT+NLGER8LgFJZCHwGqDWN1hoc2sOSbGcAqQUJf6cA0xkdtoukTQh4effQgXJPMN4pGbGVTgKFqU34AGMYpXRbnLiMCpMazwZZyIRaL1PCWDAZzuE5taMtRuR2U4EpIAX6MUrNM05GEtG2s2SFHAf96jxCPeV/Ji2yrtCCrDFTGPe+it576NkBf7O2TwNf7aVpjHyEr5JGHtorhBZzlkaF6hIMZ4WeAZ7t1nz6Q8Lgj6PJz0Je2+++CDdn01G1F1uWalccE+gaLE9WyljFMt6JEu7yq+otKCnKnVvX9mPFep8ZKE4iaWgG/JHfiU2WYjfKZLwGJu7g4+Y9ZQqwZL+4D2XqsfxjhahoDNR5xEPyl5cW8uVoWdrYfewcXArhVY=
  on:
    branch: master
    tags: true
env:
  global:
    secure: s6j10HngFDCwENqfsK6AFv1QeL7H7qTQJhCLlQ0KlIjtCxNeRPRGKeLTGxjcSTMiD5YWhp6QBrrEFeH3upvqCQcWI/IQtOG0dfI04EW2aIB/xrw7MF9aTFUmIYraqqFnsehp+7odBP/z7q92oaHdirDtVKMLPl9X1B1rHgRmiQWCvJF9W47Gb62wD0VSwN07hshe9yO9kouV0fthOqU0y/XqTATkXWzEmqbTJs+H6KS6cXYYtd8KoDgHRJDy7ClIdD8jhiPuF339gaG7Yl3lxStIOVAYO+Kxu2+PEVS25UI/JiFvZXHy83FRjsEwJF7b3IN5U2mRe/1StHt5ug9VpgOR82df8whq9xzKmLL5jff2sJuZrrp8n+EB+Hgq/7fU2eXixo3ZFrIFp8jd4EABZdBTtZYrL4VP2ohD5WOWAikHKHFs1ZHJfzNoCeL6+3h7NfD6C1DW0E4J6vuIAflV6+vIc0bX8JI+dV6Vnx0lj7xZyRHlyueXgN3JkbCeNfGXs06BazdAsQSqWkZ0GVMm93xm36ae5aGpAZYZLN1o2wh78BJtNpT9IMU/yUOOv81kmoW2f+6fOtSj3IN8pbpUFDu8Jep5hDz0HD6OoGlihjhDLSdP6kvNzoHdDBs7qsfJoZzPVtd3qIeAWI3n1zQC+vhZpLTPyDjWbmlXtxU0TFY=
